services:
  sensor-exporter:
    #build: .
    image: ghcr.io/dziban303/bmp180-exporter:latest
    container_name: pi_sensors
    hostname: pi_sensors
    restart: unless-stopped
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:ro
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=192.168.1.100
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensor/pi3_BMP180
      - UPDATE_INTERVAL=15
